# Generated by Django 5.2.1 on 2025-05-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('ESPERA', 'Em Espera')], default='PENDENTE', max_length=10),
        ),
    ]
