# Generated by Django 5.2.1 on 2025-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('ESPERA', 'Em Espera'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=10),
        ),
    ]
